name: DevOps Demo Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo apt update
            sudo apt install nginx -y
            sudo mkdir -p /var/www/html
            echo "<h1>Hello from Akshat DevOps CI/CD 🚀</h1><p>Deployed automatically from GitHub Actions</p>" | sudo tee /var/www/html/index.html > /dev/null
            sudo systemctl enable nginx
            sudo systemctl restart nginx || sudo systemctl start nginx
